/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_tool_jubian_jubianImage_routes_result$schema$value
const _deepseek_ai_dsh_tool_jubian_jubianImage_routes_result$schema = () => (_deepseek_ai_dsh_tool_jubian_jubianImage_routes_result$schema$value ??= z.object({
  'candidates': z.array(z.object({
  'standardId': z.number().readonly(),
  'platformId': z.string().readonly(),
  'unitPrice': z.union([z.literal(null), z.number()]).readonly(),
  'unit': z.union([z.literal(null), z.string()]).readonly(),
})),
}))
let _deepseek_ai_dsh_tool_jubian_jubianToken_describe_result$schema$value
const _deepseek_ai_dsh_tool_jubian_jubianToken_describe_result$schema = () => (_deepseek_ai_dsh_tool_jubian_jubianToken_describe_result$schema$value ??= z.object({
  'configured': z.boolean(),
  'source': z.string().optional(),
  'writable': z.boolean(),
}))
let _deepseek_ai_dsh_tool_jubian_jubianToken_set_parameter_0$schema$value
const _deepseek_ai_dsh_tool_jubian_jubianToken_set_parameter_0$schema = () => (_deepseek_ai_dsh_tool_jubian_jubianToken_set_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_tool_jubian_jubianToken_set_result$schema$value
const _deepseek_ai_dsh_tool_jubian_jubianToken_set_result$schema = () => (_deepseek_ai_dsh_tool_jubian_jubianToken_set_result$schema$value ??= z.object({
  'configured': z.boolean(),
  'source': z.string().optional(),
  'writable': z.boolean(),
}))
let _deepseek_ai_dsh_tool_jubian_jubianToken_unset_result$schema$value
const _deepseek_ai_dsh_tool_jubian_jubianToken_unset_result$schema = () => (_deepseek_ai_dsh_tool_jubian_jubianToken_unset_result$schema$value ??= z.object({
  'configured': z.boolean(),
  'source': z.string().optional(),
  'writable': z.boolean(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-tool-jubian',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-tool-jubian#jubianImage/routes',
      service: 'jubianImage',
      namespace: 'jubianImage',
      method: 'routes',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-tool-jubian#jubianImage/routes:result',
        create: _deepseek_ai_dsh_tool_jubian_jubianImage_routes_result$schema,
      },
      sourceLocation: {"file":"packages/jubian/tool-jubian/src/image.ts","line":131,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-tool-jubian#jubianToken/describe',
      service: 'jubianToken',
      namespace: 'jubianToken',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-credentials/types#CredentialInfo',
        create: _deepseek_ai_dsh_tool_jubian_jubianToken_describe_result$schema,
      },
      sourceLocation: {"file":"packages/jubian/tool-jubian/src/token.ts","line":66,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-tool-jubian#jubianToken/set',
      service: 'jubianToken',
      namespace: 'jubianToken',
      method: 'set',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'value',
          wire: 'value',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-tool-jubian#jubianToken/set:value',
            create: _deepseek_ai_dsh_tool_jubian_jubianToken_set_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-credentials/types#CredentialInfo',
        create: _deepseek_ai_dsh_tool_jubian_jubianToken_set_result$schema,
      },
      sourceLocation: {"file":"packages/jubian/tool-jubian/src/token.ts","line":77,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-tool-jubian#jubianToken/unset',
      service: 'jubianToken',
      namespace: 'jubianToken',
      method: 'unset',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-credentials/types#CredentialInfo',
        create: _deepseek_ai_dsh_tool_jubian_jubianToken_unset_result$schema,
      },
      sourceLocation: {"file":"packages/jubian/tool-jubian/src/token.ts","line":95,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `ctx.remote.jubianImage` namespace: the rows the paid image route may buy from. The namespace reads and never writes, and it carries rows only — the token that authorizes the read never crosses to the browser.",
        "summary": "Host service backing the generated `ctx.remote.jubianImage` namespace: the rows the paid image route may buy from.",
        "tags": [],
        "jsDoc": "/**\n * Host service backing the generated `ctx.remote.jubianImage` namespace: the rows\n * the paid image route may buy from.\n *\n * The namespace reads and never writes, and it carries rows only — the token that\n * authorizes the read never crosses to the browser.\n */",
        "key": "jubianImage",
        "exportName": "JubianImageRoutes",
        "members": [
          {
            "kind": "method",
            "name": "routes",
            "signature": "@Remote async routes(): Promise<{ candidates: ImageRouteRow[] }>",
            "summary": "List the `gpt-image-2` catalogue rows this account may buy from.",
            "jsDoc": "/**\n * List the `gpt-image-2` catalogue rows this account may buy from.\n *\n * Free and read-only: the very catalogue read the paid call makes, spending\n * nothing. A Settings page offers these rows so a person picks a platform by its\n * own price instead of reading that price out of a failure message.\n * @returns one entry per `gpt-image-2` row, in catalogue order.\n * @throws RemoteError when the catalogue cannot be read; its message is what the page shows.\n */"
          }
        ],
        "types": [
          {
            "name": "ImageRouteRow",
            "declaration": "export interface ImageRouteRow {\n    readonly standardId: number;\n    readonly platformId: string;\n    readonly unitPrice: number | null;\n    readonly unit: string | null;\n}"
          }
        ]
      },
      {
        "description": "Host service backing the generated `ctx.remote.jubianToken` namespace: the Jubian admin token as the Web Settings page reads, writes, and clears it.",
        "summary": "Host service backing the generated `ctx.remote.jubianToken` namespace: the Jubian admin token as the Web Settings page reads, writes, and clears it.",
        "tags": [],
        "jsDoc": "/**\n * Host service backing the generated `ctx.remote.jubianToken` namespace: the\n * Jubian admin token as the Web Settings page reads, writes, and clears it.\n */",
        "key": "jubianToken",
        "exportName": "JubianToken",
        "members": [
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote async describe(): Promise<CredentialInfo>",
            "summary": "Describe the stored token without reading it.",
            "jsDoc": "/**\n * Describe the stored token without reading it.\n * @returns whether a value is configured, which source supplies it, and whether this deployment can write it.\n */"
          },
          {
            "kind": "method",
            "name": "set",
            "signature": "@Remote async set(value: string): Promise<CredentialInfo>",
            "summary": "Store one value under the fixed reference.",
            "jsDoc": "/**\n * Store one value under the fixed reference.\n * @param value - the token; an empty or whitespace-only value is refused.\n * @returns the same facts {@link describe} reports after the write.\n * @throws RemoteError when the value is empty, or when the provider refuses the write.\n */"
          },
          {
            "kind": "method",
            "name": "unset",
            "signature": "@Remote async unset(): Promise<CredentialInfo>",
            "summary": "Remove the stored value.",
            "jsDoc": "/**\n * Remove the stored value. Removing an absent reference is a no-op.\n * @returns the same facts {@link describe} reports after the removal.\n * @throws RemoteError when the provider refuses the write.\n */"
          }
        ],
        "types": [
          {
            "name": "CredentialInfo",
            "declaration": "export interface CredentialInfo {\n    configured: boolean;\n    source?: string;\n    writable: boolean;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
